## Cursor style
[cursor.style]
shape = "block"

# Font settings
[font]
size = 9.5 

[font.bold]
family = "FiraCodeNerdFont"
style = "Bold"

[font.italic]
family = "FiraCodeNerdFont" 
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"

# Window settings
[window]
opacity = 0.8 
padding = { x = 10, y = 10 }

# Darker Color Scheme for Alacritty
[colors]

[colors.primary]
background = "#16161e"
foreground = "#c0caf5"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

